# File empty by default.
# Replace contents of this file with custom configuration.

[CPU-CLUSTER0-MONITOR]
algo_type           monitor
sampling            1000
sensor              cpuss-0
thresholds          60000        65000        70000
thresholds_clr      55000        60000        65000
actions             cpu-cluster0 cpu-cluster0 cpu-cluster0
action_info         1555200      1324800      1094400

[CPU-CLUSTER1-MONITOR]
algo_type           monitor
sampling            1000
sensor              cpuss-1
thresholds          65000        72000        78000
thresholds_clr      60000        67000        73000
actions             cpu-cluster1 cpu-cluster1 cpu-cluster1
action_info         1804800      1440000      1228800

[CPU-CLUSTER2-MONITOR]
algo_type           monitor
sampling            1000
sensor              cpuss-1
thresholds          67000        75000        82000
thresholds_clr      62000        70000        77000
actions             cpu-cluster2 cpu-cluster2 cpu-cluster2
action_info         2150400      1708800      1228800

[GPU-MONITOR]
algo_type           monitor
sampling            1000
sensor              gpuss-0
thresholds          70000        78000        85000
thresholds_clr      65000        73000        80000
actions             gpu          gpu          gpu
action_info         684000000    515000000    395000000

[SKIN-MONITOR]
algo_type           monitor
sampling            1000
sensor              xo-therm
thresholds          40000        42000        44000
thresholds_clr      38000        40000        42000
actions             cpu-cluster2+gpu cpu-cluster1+cpu-cluster2+gpu cpu-cluster1+cpu-cluster2+gpu+display-fps
action_info         1804800+684000000 1555200+1440000+515000000 1324800+1228800+395000000+1

[MONITOR-BACKLIGHT]
algo_type           monitor
sensor              xo-therm
actions             panel0-backlight
sampling            1000
thresholds          42000
thresholds_clr      40000
action_info         180

[MODEM-MONITOR]
algo_type           monitor
sampling            5000
sensor              mdmss-0
thresholds          65000        70000        75000
thresholds_clr      60000        65000        70000
actions             modem        modem        modem
action_info         1            2            3

[CAMERA-MONITOR]
algo_type           monitor
sampling            1000
sensor              camera-0
thresholds          60000        67000
thresholds_clr      55000        62000
actions             cpu-cluster1+cpu-cluster2+gpu  cpu-cluster1+cpu-cluster2+gpu
action_info         1555200+1708800+515000000      1324800+1440000+395000000

[WIFI-MONITOR]
algo_type           monitor
sampling            10000
sensor              wifi_therm
thresholds          55000
thresholds_clr      50000
actions             wlan
action_info         1
