# File empty by default.
# Replace contents of this file with custom configuration.

[CPU-CLUSTER0-MONITOR]
algo_type           monitor
sampling            1000
sensor              cpuss-0
thresholds          60000        65000        70000
thresholds_clr      58000        63000        68000
actions             cpu-cluster0 cpu-cluster0 cpu-cluster0
action_info         1708800      1555200      1228800

[CPU-CLUSTER1-MONITOR]
algo_type           monitor
sampling            1000
sensor              cpuss-1
thresholds          65000        75000        85000
thresholds_clr      60000        70000        80000
actions             cpu-cluster1 cpu-cluster1 cpu-cluster1
action_info         2150400      1804800      1555200

[CPU-CLUSTER2-MONITOR]
algo_type           monitor
sampling            1000
sensor              cpuss-1
thresholds          68000        78000        88000
thresholds_clr      63000        73000        83000
actions             cpu-cluster2 cpu-cluster2 cpu-cluster2
action_info         2611200      2150400      1804800

[GPU-MONITOR]
algo_type           monitor
sampling            1000
sensor              gpuss-0
thresholds          75000        85000        90000
thresholds_clr      70000        80000        85000
actions             gpu          gpu          gpu
action_info         800000000    684000000    515000000

[SKIN-MONITOR]
algo_type           monitor
sampling            2000
sensor              xo-therm
thresholds          41000        43000        45000
thresholds_clr      39000        41000        43000
actions             cpu-cluster2+gpu cpu-cluster1+cpu-cluster2+gpu cpu-cluster1+cpu-cluster2+gpu+display-fps
action_info         2150400+800000000 1804800+1555200+684000000 1555200+1228800+515000000+1

[MONITOR-BACKLIGHT]
algo_type           monitor
sensor              xo-therm
actions             panel0-backlight
sampling            2000
thresholds          44000
thresholds_clr      42000
action_info         180
